### ISSUE TITLE
View breweries/bar by location

### ISSUE THREAD

**Issue by emilyadarr** [emilyadarr/pursuit-of-hoppyness#6]
WHEN I search for a city
THEN I am presented with breweries and bars located in the city

WHEN brewery and bar locations load
THEN I can view that locations address, web address, link to more info

Connect OpenBrewery API to fetch breweries/bars by location and beer type
Dynamically create cards/elements with breweries/bars address, web address (& Button?)

**Comment by Thoma77s** [comment]
All Done!
